---
- name: "student container"
  become: yes
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Removing a file
      file:
        path: ./student-list
        state: absent

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: "https://github.com/joriscommin/student-list.git"
        dest:  student-list

    - name: "Copy text in daemon.json"
      copy:
        content: { 'insecure-registries' :['192.168.31.131:5000'] }
        dest: /etc/docker/daemon.json

    - name: Start and enable the Docker daemon
      service:
        name: docker 
        state: started 
        enabled: yes


    - name: Create  containers
      docker_container:
        name: "student-api"
        image: "192.168.31.131:5000/student-api"
        ports: 80:5000

    - name: Create  containers
      docker_container:
        name: "website"
        image: "php:apache"
        ports: 8080:80
        env:
          USERNAME=toto
          PASSWORD=python
        volumes:
          - ./student-list/website:/var/www/html
    - name: Add a container to a network, leaving existing containers connected
      docker_network:
        name: network_one
        connected:
          - student-api
          - website
        appends: yes

...

