---
- name: "Tests"
  hosts: client
  tasks:
    - name: Test 
      uri:
        url: "http://192.168.31.132:8080"
        method: GET
        return_content: yes
      register: this
      failed_when: "'Student' not in this.content"
...

